apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - stepzen-admin-cmd-job-role.yaml
  - stepzen-admin-cmd-job-rb.yaml
  - stepzen-admin-cmd-job-sa.yaml
  - stepzen-admin-cmd-job.yaml
