kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stepzen-admin-cmd-job-rb
subjects:
- kind: ServiceAccount
  name: stepzen-admin-cmd-job-sa
  namespace: cp4i
roleRef:
 kind: Role
 name: stepzen-admin-cmd-job-role
 apiGroup: rbac.authorization.k8s.io