apiVersion: batch/v1
kind: Job
metadata:
  name: create-stepzen-db-secret
spec:
  template:
    metadata:
      name: create-stepzen-db-secret
    spec:
      serviceAccount: create-stepzen-db-secret-job-sa
      containers:
        - name: client
          image: registry.redhat.io/openshift4/ose-cli
          envFrom:
            - secretRef:
                name: stepzen-db-pguser-stepzen
                optional: false
          command: ["/bin/bash"]
          args:
            - "-c"
            - oc create secret generic stepzen-db-secret --from-literal=DSN=${uri}
      restartPolicy: Never

  