apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql.yaml
  - create-stepzen-db-secret-job-role.yaml
  - create-stepzen-db-secret-job-rb.yaml
  - create-stepzen-db-secret-job-sa.yaml
  - create-stepzen-db-secret-job.yaml
